version: '2.1'

services:

  roomer_api:
    container_name: roomer_api
    build: ./roomerDjango
    command: bash -c "python3.8 manage.py makemigrations roomerApi && python3.8 manage.py migrate && python3.8 manage.py fill_db 300 && python3.8 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    container_name: postgresql
    image: "postgres:alpine"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "4000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5