# Generated by Django 4.1.3 on 2022-12-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomerApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='deposit',
        ),
    ]
